[project]
name = "viewpane"
version = "1.0.0"
requires-python = ">=3.8,<4.0"

[tool.black]
line-length = 119
target_version = ["py38"]

[tool.mypy]
warn_unused_configs = true
ignore_missing_imports = true
